// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwOxtdq_ndHHLEEIAf1rb-xNIjCNHJ2S0',
    appId: '1:792267200874:web:d7693285cdb17cbd8c2d13',
    messagingSenderId: '792267200874',
    projectId: 'heritagemapapp',
    authDomain: 'heritagemapapp.firebaseapp.com',
    storageBucket: 'heritagemapapp.appspot.com',
    measurementId: 'G-JJDDLQNQQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvcjgMRP6QEK5zZChsLvgRa9BrQsxhqSc',
    appId: '1:792267200874:android:520542b930cdd0e88c2d13',
    messagingSenderId: '792267200874',
    projectId: 'heritagemapapp',
    storageBucket: 'heritagemapapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR1V13DbAc1xDK-3NOQvm5PausBCFO5lU',
    appId: '1:792267200874:ios:d45f25ab8f70e5278c2d13',
    messagingSenderId: '792267200874',
    projectId: 'heritagemapapp',
    storageBucket: 'heritagemapapp.appspot.com',
    iosBundleId: 'com.example.heritageMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR1V13DbAc1xDK-3NOQvm5PausBCFO5lU',
    appId: '1:792267200874:ios:6fb2a8751a6ba1538c2d13',
    messagingSenderId: '792267200874',
    projectId: 'heritagemapapp',
    storageBucket: 'heritagemapapp.appspot.com',
    iosBundleId: 'com.example.heritageMap.RunnerTests',
  );
}
